### ISSUE TITLE
KeyError: 'Contig'

### ISSUE THREAD

**Issue by htaohan** [metagentools/MetaCoAG#32]
metacoag --assembler megahit --graph final.contigs.gfa --contigs final.contigs.fa --abundance abundance.tsv --output /xx/short_real_result/Metacoag

Traceback (most recent call last):
  File "/xx/tools/MetaCoAG-develop/metacoag", line 1066, in <module>
    main()
  File "/xx/tools/MetaCoAG-develop/metacoag", line 279, in main
    ) = feature_utils.get_cov_len_megahit(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xx/tools/MetaCoAG-develop/metacoag_utils/feature_utils.py", line 194, in get_cov_len_megahit
    contig_num = contig_names_rev[graph_to_contig_map_rev[strings[0]]]
                                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Contig'


abundance file header:
![image](https://user-images.githubusercontent.com/49517797/235825364-a02a5ca0-b7e8-4eb1-bf70-a5371f822788.png)

I am sorry to bother you. I follow the pipeline but ran into problems, how can i fix it?

**Comment by Vini2** [comment]
Hi @masterhan666,

Just remove the first line (starting with `Contig final.contigs.fa/...`) of the abundance file and try running again.
MetaCoAG expects the abundance file without the header row.

Let me know how it goes.

**Comment by Vini2** [comment]
Closing issue due to inactivity. Please re-open if needed.
